name: pihole-unbound

services:
  pihole-unbound:
    image: pihole-unbound:latest
    container_name: pihole-unbound
    hostname: pihole-unbound
    build: .
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${PIHOLE_WEBPORT:-80}:80/tcp"
      - "5335:5335/tcp"
      - "5335:5335/udp"
    environment:
      TZ: "${TZ}"
      WEBPASSWORD: "${WEBPASSWORD}"
      PIHOLE_DNS_: "${PIHOLE_DNS_}"
      FTLCONF_LOCAL_IPV4: "${FTLCONF_LOCAL_IPV4}"
      ADLISTS: "${ADLISTS}"
      LOCALDNS: "${LOCALDNS}"
      CNAME_ENTRIES: "${CNAME_ENTRIES}"
      DNSMASQ_LISTENING: "${DNSMASQ_LISTENING}"
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d
      - unbound_data:/etc/unbound
      - unbound_logs:/var/log/unbound
      - pihole_logs:/var/log/pihole.log
    restart: unless-stopped

volumes:
  pihole_data:
  dnsmasq_data:
  unbound_data:
  unbound_logs:
  pihole_logs:
