#!/bin/bash
UNBOUND_ANCHOR_EXEC=/usr/sbin/unbound-anchor

$UNBOUND_ANCHOR_EXEC -a /var/lib/unbound/root.key

UNBOUND_EXEC=/usr/sbin/unbound
$UNBOUND_EXEC -d

if [ $? -eq 0 ]; then
    echo "Unbound started successfully."
else
    echo "Failed to start Unbound."
    exit 1
fi